{% set name = "typing_extensions" %}
{% set version = "3.10.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49f75d16ff11f1cd258e1b988ccff82a3ca5570217d7ad8c5f48205dd99a677e

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install --no-deps --ignore-installed .
      noarch: python

    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
        - wheel
      run:
        - python >=3.6

    test:
      imports:
        - typing_extensions

  - name: typing-extensions
    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - typing_extensions
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/python/typing/tree/master/typing_extensions
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Backported and Experimental Type Hints for Python
  description: |
    The typing module was added to the standard library in Python 3.5, but
    many new features have been added to the module since then.
    This means users of older Python versions who are unable to upgrade will not be
    able to take advantage of new types added to the typing module, such as
    typing.Protocol or typing.TypedDict.
    
    The typing_extensions module contains backports of these changes.
    Experimental types that will eventually be added to the ``typing``
    module are also included in typing_extensions.

  doc_url: https://github.com/python/typing
  dev_url: https://github.com/python/typing

extra:
  recipe-maintainers:
    - djsutherland
