travis:
  secure:
    BINSTAR_TOKEN: q9i9cZzTOypemupTdQ7aI2JJxv7/zoajSqizriMpokO85X/YuLB/ekbFnioyGmyinbRi8oZG0fx+qPa+85g2udPraHYn/5TdHm+xEm8GqsSeppLfUJ9Tet2M1hSn0c/aNX2yEBYwBAaNIBPmPs8X7PgbA2GWpsqCM7ko0xZWC6xpHpYLNfyVn+C4mgb0veGGWjI/9uV/wFoRNRFbXF5rcyBvGgY261NT27WancM660bb8ljU0Oi6Npn9uzye3HeDaA22G3Pt4DAK0OLQbvPMB5mP9lP1IYRLJqKVi9V/P9ej6w2yJM3CGG0sOnBTEGPBCwNkXWkAqtq1YoB1cd72q50OK+ipX6vysWbXRIPqweoiPfAs0c51zjVkP2VtlztDz7zXk3WCPeKR84uRlftkE7ObaC+W8icgxFms4YiHAHt4GCoopgPk0OvIGRw7P+yJ9TBddQAiYm7nJ47JKMBkp9nrHrrUgK6qMwk2ipeJ3D74s1kl0ZNT/DaVd/Ybx2xCFaHOMa1vCbqoCXjvnR58Ago5W+BJeU1UXj+wZusBUpRCIIFvuRoRUCmcQKVXzYhIlO+QUQqC4TrMGcrEB+zCyYMyJ0UlvzndKQAzowCRkURfRFpQCZRgmSd+oIWvqiBdSqXCID6AuySJNwMESmx8pQdWOnnf74Caw67zkdkSh1k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
